package vista;

public class VistaLista extends javax.swing.JFrame {

    public VistaLista() {
        initComponents();
    }

    /**
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnNuevaLista = new javax.swing.JButton();
        scrollLista = new javax.swing.JScrollPane();
        listaRutas = new javax.swing.JList<>();
        scrollRutaLista = new javax.swing.JScrollPane();
        tablaRutaLista = new javax.swing.JList<>();
        btnCerrar = new javax.swing.JButton();
        btnQuitarRuta = new javax.swing.JButton();
        btnEliminarLista = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelHeader.setBackground(new java.awt.Color(45, 80, 22));
        panelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Mis listas");
        panelHeader.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        btnNuevaLista.setText("+ Nueva lista");
        panelHeader.add(btnNuevaLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(609, 23, 110, 30));

        listaRutas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollLista.setViewportView(listaRutas);

        tablaRutaLista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollRutaLista.setViewportView(tablaRutaLista);

        btnCerrar.setText("Cerrar");

        btnQuitarRuta.setText("Quitar ruta");

        btnEliminarLista.setText("Eliminar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminarLista)
                    .addComponent(scrollLista, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnQuitarRuta)
                        .addGap(172, 172, 172)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(scrollRutaLista)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollLista, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(scrollRutaLista))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(btnQuitarRuta)
                    .addComponent(btnEliminarLista))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // getters para el controlador
    public javax.swing.JList<String> getListaListas()    { return listaRutas; }
    public javax.swing.JList<String> getTablaRutaLista() { return tablaRutaLista; }
    public javax.swing.JButton getBtnNuevaLista()    { return btnNuevaLista; }
    public javax.swing.JButton getBtnEliminarLista() { return btnEliminarLista; }
    public javax.swing.JButton getBtnQuitarRuta()    { return btnQuitarRuta; }
    public javax.swing.JButton getBtnCerrar()        { return btnCerrar; }

    public void setModeloListas(javax.swing.DefaultListModel<String> modelo) {
        listaRutas.setModel(modelo);
    }
    public void setModeloRutas(javax.swing.DefaultListModel<String> modelo) {
        tablaRutaLista.setModel(modelo);
    }
    public void mostrarMensaje(String msg) { javax.swing.JOptionPane.showMessageDialog(this, msg); }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEliminarLista;
    private javax.swing.JButton btnNuevaLista;
    private javax.swing.JButton btnQuitarRuta;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JList<String> listaRutas;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JScrollPane scrollLista;
    private javax.swing.JScrollPane scrollRutaLista;
    private javax.swing.JList<String> tablaRutaLista;
    // End of variables declaration//GEN-END:variables
}
