/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author aniki
 */
public class VistaPaginaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPaginaPrincipal
     */
    public VistaPaginaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        lblNombreApp = new javax.swing.JLabel();
        lblBienvenida = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        scrollTabla = new javax.swing.JScrollPane();
        tablaRutas = new javax.swing.JTable();
        toolBar = new javax.swing.JToolBar();
        btnNuevaRuta = new javax.swing.JButton();
        btnVerRuta = new javax.swing.JButton();
        btnEditarRuta = new javax.swing.JButton();
        btnBorrarRuta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHeader.setBackground(new java.awt.Color(45, 80, 22));
        panelHeader.setAlignmentX(0.0F);
        panelHeader.setAlignmentY(0.0F);

        lblNombreApp.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblNombreApp.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreApp.setText("TrailMate");

        lblBienvenida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBienvenida.setForeground(new java.awt.Color(159, 191, 128));
        lblBienvenida.setText("Hola, ");

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LogoTrailMate60.png"))); // NOI18N

        btnCerrarSesion.setText("Cerrar sesión");

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNombreApp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 299, Short.MAX_VALUE)
                .addComponent(lblBienvenida)
                .addGap(128, 128, 128)
                .addComponent(btnCerrarSesion)
                .addGap(15, 15, 15))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelHeaderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelHeaderLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreApp)
                            .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBienvenida))))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(panelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 80));

        tablaRutas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Ubicación", "Dificultad", "Valoración"
            }
        ));
        tablaRutas.setColumnSelectionAllowed(true);
        tablaRutas.setGridColor(new java.awt.Color(224, 224, 224));
        tablaRutas.setRowHeight(28);
        scrollTabla.setViewportView(tablaRutas);
        tablaRutas.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        getContentPane().add(scrollTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 740, 280));

        toolBar.setBackground(new java.awt.Color(204, 204, 204));
        toolBar.setRollover(true);
        toolBar.setAlignmentX(0.0F);
        toolBar.setAlignmentY(55.0F);

        btnNuevaRuta.setBackground(new java.awt.Color(45, 80, 22));
        btnNuevaRuta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNuevaRuta.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevaRuta.setText("+ Nueva");
        toolBar.add(btnNuevaRuta);

        btnVerRuta.setText("Ver");
        toolBar.add(btnVerRuta);

        btnEditarRuta.setText("Editar");
        toolBar.add(btnEditarRuta);

        btnBorrarRuta.setForeground(new java.awt.Color(163, 45, 45));
        btnBorrarRuta.setText("Borrar");
        toolBar.add(btnBorrarRuta);

        getContentPane().add(toolBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 740, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPaginaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarRuta;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnEditarRuta;
    private javax.swing.JButton btnNuevaRuta;
    private javax.swing.JButton btnVerRuta;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNombreApp;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JScrollPane scrollTabla;
    private javax.swing.JTable tablaRutas;
    private javax.swing.JToolBar toolBar;
    // End of variables declaration//GEN-END:variables
}
