package vista;

public class VistaLogin extends javax.swing.JFrame {

    public VistaLogin() {
        initComponents();
    }

    /**
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMarca = new javax.swing.JPanel();
        lblSubtituloApp = new javax.swing.JLabel();
        lblNombreApp = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        PanelDerecho = new javax.swing.JPanel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        btnRegistro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelMarca.setBackground(new java.awt.Color(45, 80, 22));
        PanelMarca.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSubtituloApp.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblSubtituloApp.setForeground(new java.awt.Color(159, 191, 128));
        lblSubtituloApp.setText("rutas de senderismo");
        lblSubtituloApp.setToolTipText("");
        PanelMarca.add(lblSubtituloApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        lblNombreApp.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblNombreApp.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreApp.setText("TrailMate");
        lblNombreApp.setToolTipText("");
        PanelMarca.add(lblNombreApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, 30));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LogoTrailMate130.png"))); // NOI18N
        PanelMarca.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 130, 120));

        getContentPane().add(PanelMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 340));

        PanelDerecho.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEmail.setText("Email");
        PanelDerecho.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        txtEmail.setColumns(20);
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        PanelDerecho.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 250, 30));

        lblPassword.setText("Contraseña");
        PanelDerecho.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        txtPassword.setColumns(20);
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        PanelDerecho.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 250, 40));

        btnLogin.setBackground(new java.awt.Color(45, 80, 22));
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.setFocusPainted(false);
        PanelDerecho.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 250, 40));

        btnRegistro.setBackground(new java.awt.Color(45, 80, 22));
        btnRegistro.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistro.setText("¿No tienes cuenta? Registrate.");
        btnRegistro.setBorderPainted(false);
        PanelDerecho.add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        getContentPane().add(PanelDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 330, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
    }//GEN-LAST:event_txtPasswordActionPerformed

    // getters para el controlador
    public String getEmail()    { return txtEmail.getText(); }
    public String getPassword() { return txtPassword.getText(); } // pendiente cambiar a JPasswordField
    public javax.swing.JButton getBtnLogin()    { return btnLogin; }
    public javax.swing.JButton getBtnRegistro() { return btnRegistro; }
    public void mostrarMensaje(String msg) { javax.swing.JOptionPane.showMessageDialog(this, msg); }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelDerecho;
    private javax.swing.JPanel PanelMarca;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNombreApp;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSubtituloApp;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables
}
