package vista;

public class VistaRuta extends javax.swing.JFrame {

    public VistaRuta() {
        initComponents();
        aplicarEstilo();
    }

    private void aplicarEstilo() {
        java.awt.Color fondoOscuro  = new java.awt.Color(45, 45, 45);
        java.awt.Color fondoChip    = new java.awt.Color(58, 58, 58);
        java.awt.Color fondoCampo   = new java.awt.Color(64, 64, 64);
        java.awt.Color textoBlanco  = new java.awt.Color(255, 255, 255);
        java.awt.Color textoGris    = new java.awt.Color(170, 170, 170);

        getContentPane().setBackground(fondoOscuro);

        // chips de datos
        panelUbicacion.setBackground(fondoChip);
        panelValoracion.setBackground(fondoChip);
        panelLongitud.setBackground(fondoChip);
        lblUbicacion.setForeground(textoGris);    lblValorUbicacion.setForeground(textoBlanco);
        lblValoracion.setForeground(textoGris);   lblValorValoracion.setForeground(textoBlanco);
        lblLongitud.setForeground(textoGris);     lblValorLongitud.setForeground(textoBlanco);

        // etiquetas generales
        lblNombreRuta.setForeground(textoBlanco);
        lblDificultad.setForeground(textoGris);
        lblAutor.setForeground(textoGris);
        lblDescripcion.setForeground(textoGris);
        lblNuevoComentario.setForeground(textoGris);
        lblComentarios.setForeground(textoGris);

        // área descripción
        areaDescripcion.setBackground(fondoCampo);
        areaDescripcion.setForeground(textoBlanco);
        areaDescripcion.setCaretColor(textoBlanco);

        // comentarios
        listComentarios.setBackground(fondoCampo);
        listComentarios.setForeground(textoBlanco);
        txtNuevoComentario.setBackground(fondoCampo);
        txtNuevoComentario.setForeground(textoBlanco);
        txtNuevoComentario.setCaretColor(textoBlanco);
        txtNuevoComentario.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 8, 4, 8));

        // alineación centrada del valor en los chips
        lblValorValoracion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValorLongitud.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValorUbicacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        // botones inferiores acorde al tema oscuro
        java.awt.Color fondoBoton = new java.awt.Color(64, 64, 64);
        btnValorar.setBackground(fondoBoton);
        btnValorar.setForeground(textoBlanco);
        btnValorar.setFocusPainted(false);
        btnGuardarEnLista.setBackground(fondoBoton);
        btnGuardarEnLista.setForeground(textoBlanco);
        btnGuardarEnLista.setFocusPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUbicacion = new javax.swing.JPanel();
        lblUbicacion = new javax.swing.JLabel();
        lblValorUbicacion = new javax.swing.JLabel();
        panelValoracion = new javax.swing.JPanel();
        lblValoracion = new javax.swing.JLabel();
        lblValorValoracion = new javax.swing.JLabel();
        panelLongitud = new javax.swing.JPanel();
        lblLongitud = new javax.swing.JLabel();
        lblValorLongitud = new javax.swing.JLabel();
        lblNombreRuta = new javax.swing.JLabel();
        btnValorar = new javax.swing.JButton();
        btnGuardarEnLista = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        lblDificultad = new javax.swing.JLabel();
        scrollDescripcion = new javax.swing.JScrollPane();
        areaDescripcion = new javax.swing.JTextArea();
        lblAutor = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        scrollComentarios = new javax.swing.JScrollPane();
        listComentarios = new javax.swing.JList<>();
        txtNuevoComentario = new javax.swing.JTextField();
        lblNuevoComentario = new javax.swing.JLabel();
        lblComentarios = new javax.swing.JLabel();
        btnComentar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUbicacion.setText("ubicación");

        lblValorUbicacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout panelUbicacionLayout = new javax.swing.GroupLayout(panelUbicacion);
        panelUbicacion.setLayout(panelUbicacionLayout);
        panelUbicacionLayout.setHorizontalGroup(
            panelUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUbicacionLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(panelUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblValorUbicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUbicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        panelUbicacionLayout.setVerticalGroup(
            panelUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUbicacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblValorUbicacion, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblUbicacion)
                .addContainerGap())
        );

        getContentPane().add(panelUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 140, 70));

        lblValoracion.setText("valoración");

        lblValorValoracion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout panelValoracionLayout = new javax.swing.GroupLayout(panelValoracion);
        panelValoracion.setLayout(panelValoracionLayout);
        panelValoracionLayout.setHorizontalGroup(
            panelValoracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelValoracionLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(panelValoracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblValorValoracion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblValoracion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        panelValoracionLayout.setVerticalGroup(
            panelValoracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelValoracionLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblValorValoracion, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblValoracion)
                .addContainerGap())
        );

        getContentPane().add(panelValoracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 140, 70));

        lblLongitud.setText("longitud");

        lblValorLongitud.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout panelLongitudLayout = new javax.swing.GroupLayout(panelLongitud);
        panelLongitud.setLayout(panelLongitudLayout);
        panelLongitudLayout.setHorizontalGroup(
            panelLongitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLongitudLayout.createSequentialGroup()
                .addGroup(panelLongitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLongitudLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(lblLongitud))
                    .addGroup(panelLongitudLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblValorLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        panelLongitudLayout.setVerticalGroup(
            panelLongitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLongitudLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(lblValorLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLongitud)
                .addContainerGap())
        );

        getContentPane().add(panelLongitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 140, 70));

        lblNombreRuta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(lblNombreRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 260, 40));

        btnValorar.setText("Valorar");
        getContentPane().add(btnValorar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 90, 30));

        btnGuardarEnLista.setText("Guardar en lista");
        getContentPane().add(btnGuardarEnLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 510, 140, 30));

        btnCerrar.setBackground(new java.awt.Color(45, 80, 22));
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("Volver");
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 510, 90, 30));

        lblDificultad.setText("Dificultad");
        getContentPane().add(lblDificultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 120, 40));

        areaDescripcion.setEditable(false);
        areaDescripcion.setColumns(20);
        areaDescripcion.setLineWrap(true);
        areaDescripcion.setRows(5);
        areaDescripcion.setWrapStyleWord(true);
        scrollDescripcion.setViewportView(areaDescripcion);

        getContentPane().add(scrollDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 450, -1));

        lblAutor.setText("Por: ");
        getContentPane().add(lblAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        lblDescripcion.setText("Descripción");
        getContentPane().add(lblDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        listComentarios.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollComentarios.setViewportView(listComentarios);

        getContentPane().add(scrollComentarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 450, 110));
        getContentPane().add(txtNuevoComentario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 450, -1));

        lblNuevoComentario.setText("Nuevo comentario");
        getContentPane().add(lblNuevoComentario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        lblComentarios.setText("Comentarios");
        getContentPane().add(lblComentarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        btnComentar.setBackground(new java.awt.Color(45, 80, 22));
        btnComentar.setForeground(new java.awt.Color(255, 255, 255));
        btnComentar.setText("Comentar");
        getContentPane().add(btnComentar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, -1, -1));

        jLabel1.setText("Dificultad: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 60, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // setters que usa el controlador para cargar los datos de la ruta
    public void setNombreRuta(String s)  { lblNombreRuta.setText(s); }
    public void setDificultad(String s)  { lblDificultad.setText(s); }
    public void setAutor(String s)       { lblAutor.setText("Por: " + s); }
    public void setLongitud(String s)    { lblValorLongitud.setText(s); }
    public void setUbicacion(String s)   { lblValorUbicacion.setText(s); }
    public void setValoracion(String s)  { lblValorValoracion.setText(s); }
    public void setDescripcion(String s) { areaDescripcion.setText(s); }

    public javax.swing.JButton getBtnCerrar()        { return btnCerrar; }
    public javax.swing.JButton getBtnValorar()       { return btnValorar; }
    public javax.swing.JButton getBtnGuardarEnLista(){ return btnGuardarEnLista; }
    public javax.swing.JButton getBtnComentar()      { return btnComentar; }

    public String getNuevoComentario() { return txtNuevoComentario.getText(); }
    public void limpiarComentario()    { txtNuevoComentario.setText(""); }
    public void setComentarios(javax.swing.DefaultListModel<String> modelo) {
        listComentarios.setModel(modelo);
    }
    public void mostrarMensaje(String msg) { javax.swing.JOptionPane.showMessageDialog(this, msg); }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaDescripcion;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnComentar;
    private javax.swing.JButton btnGuardarEnLista;
    private javax.swing.JButton btnValorar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblComentarios;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblDificultad;
    private javax.swing.JLabel lblLongitud;
    private javax.swing.JLabel lblNombreRuta;
    private javax.swing.JLabel lblNuevoComentario;
    private javax.swing.JLabel lblUbicacion;
    private javax.swing.JLabel lblValorLongitud;
    private javax.swing.JLabel lblValorUbicacion;
    private javax.swing.JLabel lblValorValoracion;
    private javax.swing.JLabel lblValoracion;
    private javax.swing.JList<String> listComentarios;
    private javax.swing.JPanel panelLongitud;
    private javax.swing.JPanel panelUbicacion;
    private javax.swing.JPanel panelValoracion;
    private javax.swing.JScrollPane scrollComentarios;
    private javax.swing.JScrollPane scrollDescripcion;
    private javax.swing.JTextField txtNuevoComentario;
    // End of variables declaration//GEN-END:variables
}
