package vista;

public class VistaRegistro extends javax.swing.JFrame {

    public VistaRegistro() {
        initComponents();
        aplicarEstilo();
    }

    /**
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImagen = new javax.swing.JPanel();
        lblFotoRegistro = new javax.swing.JLabel();
        lblSlogan = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PanelDerecho = new javax.swing.JPanel();
        txtEmail = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtConfirmar = new javax.swing.JPasswordField();
        txtPassword = new javax.swing.JPasswordField();
        btnRegistrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelImagen.setBackground(new java.awt.Color(58, 90, 28));

        lblFotoRegistro.setBackground(new java.awt.Color(58, 90, 28));
        lblFotoRegistro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFotoRegistro.setForeground(new java.awt.Color(255, 255, 255));
        lblFotoRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFotoRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logos/ImagenRegistro.jpg"))); // NOI18N
        lblFotoRegistro.setText("foto");
        lblFotoRegistro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(159, 191, 128)));

        lblSlogan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSlogan.setForeground(new java.awt.Color(255, 255, 255));
        lblSlogan.setText("Únete a la comunidad");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Comparte tus rutas favoritas");

        javax.swing.GroupLayout panelImagenLayout = new javax.swing.GroupLayout(panelImagen);
        panelImagen.setLayout(panelImagenLayout);
        panelImagenLayout.setHorizontalGroup(
            panelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImagenLayout.createSequentialGroup()
                .addGroup(panelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelImagenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFotoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(panelImagenLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(panelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSlogan)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImagenLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(11, 11, 11)))
                        .addGap(0, 48, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelImagenLayout.setVerticalGroup(
            panelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImagenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFotoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSlogan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        getContentPane().add(panelImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 380));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        btnRegistrar.setBackground(new java.awt.Color(45, 80, 22));
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Crear cuenta");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        jLabel1.setText("NOMBRE");

        jLabel2.setText("CONTRASEÑA");

        jLabel3.setText("EMAIL");

        jLabel4.setText("CONFIRMAR");

        jButton1.setText("Volver al login");

        javax.swing.GroupLayout PanelDerechoLayout = new javax.swing.GroupLayout(PanelDerecho);
        PanelDerecho.setLayout(PanelDerechoLayout);
        PanelDerechoLayout.setHorizontalGroup(
            PanelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDerechoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDerechoLayout.createSequentialGroup()
                        .addGroup(PanelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(PanelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addGroup(PanelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtConfirmar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                        .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING)))))
                        .addGap(124, 124, 124))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDerechoLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(50, 50, 50))))
        );
        PanelDerechoLayout.setVerticalGroup(
            PanelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDerechoLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(7, 7, 7)
                .addComponent(txtConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        getContentPane().add(PanelDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 280, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
    }//GEN-LAST:event_btnRegistrarActionPerformed

    // getters para el controlador
    public String getNombre()      { return txtNombre.getText(); }
    public String getEmail()       { return txtEmail.getText(); }
    public String getPass()        { return new String(txtPassword.getPassword()); }
    public String getPassConfirm() { return new String(txtConfirmar.getPassword()); }
    public javax.swing.JButton getBtnRegistrar()   { return btnRegistrar; }
    public javax.swing.JButton getBtnVolverLogin() { return jButton1; }
    public void mostrarMensaje(String msg) { javax.swing.JOptionPane.showMessageDialog(this, msg); }

    private void aplicarEstilo() {
        java.awt.Color fondoOscuro = new java.awt.Color(45, 45, 45);
        java.awt.Color fondoCampo  = new java.awt.Color(64, 64, 64);
        java.awt.Color textoBlanco = new java.awt.Color(255, 255, 255);
        java.awt.Color textoGris   = new java.awt.Color(170, 170, 170);
        javax.swing.border.Border camposBorder = javax.swing.BorderFactory.createEmptyBorder(4, 8, 4, 8);

        getContentPane().setBackground(fondoOscuro); // elimina la franja blanca entre paneles
        PanelDerecho.setBackground(fondoOscuro);

        jLabel1.setForeground(textoBlanco);
        jLabel2.setForeground(textoBlanco);
        jLabel3.setForeground(textoBlanco);
        jLabel4.setForeground(textoBlanco);

        txtNombre.setBackground(fondoCampo);   txtNombre.setForeground(textoBlanco);   txtNombre.setCaretColor(textoBlanco);   txtNombre.setBorder(camposBorder);
        txtEmail.setBackground(fondoCampo);    txtEmail.setForeground(textoBlanco);    txtEmail.setCaretColor(textoBlanco);    txtEmail.setBorder(camposBorder);
        txtPassword.setBackground(fondoCampo); txtPassword.setForeground(textoBlanco); txtPassword.setCaretColor(textoBlanco); txtPassword.setBorder(camposBorder);
        txtConfirmar.setBackground(fondoCampo);txtConfirmar.setForeground(textoBlanco);txtConfirmar.setCaretColor(textoBlanco);txtConfirmar.setBorder(camposBorder);

        // "login" resaltado en verde con subrayado
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setText("<html><font color='#CCCCCC'>Volver al </font><u><font color='#9FBF80'>login</font></u></html>");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelDerecho;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblFotoRegistro;
    private javax.swing.JLabel lblSlogan;
    private javax.swing.JPanel panelImagen;
    private javax.swing.JPasswordField txtConfirmar;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
