package vista;

public class VistaPaginaPrincipal extends javax.swing.JFrame {

    public VistaPaginaPrincipal() {
        initComponents();
        aplicarEstilo();
    }

    private void aplicarEstilo() {
        java.awt.Color fondoOscuro  = new java.awt.Color(45, 45, 45);
        java.awt.Color fondoPanel   = new java.awt.Color(58, 58, 58);
        java.awt.Color textoBlanco  = new java.awt.Color(255, 255, 255);
        java.awt.Color textoGris    = new java.awt.Color(200, 200, 200);

        // fondo general
        getContentPane().setBackground(fondoOscuro);

        // toolbar
        toolBar.setBackground(fondoPanel);

        // botones de toolbar sin estilo propio
        btnVerRuta.setBackground(fondoPanel);    btnVerRuta.setForeground(textoBlanco);
        btnEditarRuta.setBackground(fondoPanel); btnEditarRuta.setForeground(textoBlanco);
        btnBorrarRuta.setBackground(fondoPanel);
        btnMisListas.setBackground(fondoPanel);  btnMisListas.setForeground(textoBlanco);

        // tabla
        tablaRutas.setBackground(fondoOscuro);
        tablaRutas.setForeground(textoBlanco);
        tablaRutas.setGridColor(new java.awt.Color(70, 70, 70));
        tablaRutas.setSelectionBackground(new java.awt.Color(45, 80, 22));
        tablaRutas.setSelectionForeground(textoBlanco);
        tablaRutas.getTableHeader().setBackground(fondoPanel);
        tablaRutas.getTableHeader().setForeground(textoGris);
        scrollTabla.getViewport().setBackground(fondoOscuro);
        scrollTabla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(70, 70, 70)));

        // botón cerrar sesión blanco sobre header verde
        btnCerrarSesion.setBackground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setForeground(new java.awt.Color(45, 80, 22));
        btnCerrarSesion.setFocusPainted(false);
        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }

    /**
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        lblNombreApp = new javax.swing.JLabel();
        lblBienvenida = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        scrollTabla = new javax.swing.JScrollPane();
        tablaRutas = new javax.swing.JTable();
        toolBar = new javax.swing.JToolBar();
        btnNuevaRuta = new javax.swing.JButton();
        btnVerRuta = new javax.swing.JButton();
        btnEditarRuta = new javax.swing.JButton();
        btnBorrarRuta = new javax.swing.JButton();
        btnMisListas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHeader.setBackground(new java.awt.Color(45, 80, 22));
        panelHeader.setAlignmentX(0.0F);
        panelHeader.setAlignmentY(0.0F);

        lblNombreApp.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblNombreApp.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreApp.setText("TrailMate");

        lblBienvenida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBienvenida.setForeground(new java.awt.Color(159, 191, 128));
        lblBienvenida.setText("Hola, ");

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logos/LogoTrailMatePrincipal.png"))); // NOI18N

        btnCerrarSesion.setText("Cerrar sesión");

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombreApp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 319, Short.MAX_VALUE)
                .addComponent(lblBienvenida)
                .addGap(108, 108, 108)
                .addComponent(btnCerrarSesion)
                .addGap(15, 15, 15))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreApp)
                    .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBienvenida))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(panelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 80));

        tablaRutas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Ubicación", "Dificultad", "Valoración"
            }
        ));
        tablaRutas.setColumnSelectionAllowed(true);
        tablaRutas.setGridColor(new java.awt.Color(224, 224, 224));
        tablaRutas.setRowHeight(28);
        scrollTabla.setViewportView(tablaRutas);
        tablaRutas.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        getContentPane().add(scrollTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 740, 280));

        toolBar.setBackground(new java.awt.Color(204, 204, 204));
        toolBar.setRollover(true);
        toolBar.setAlignmentX(0.0F);
        toolBar.setAlignmentY(55.0F);

        btnNuevaRuta.setBackground(new java.awt.Color(45, 80, 22));
        btnNuevaRuta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNuevaRuta.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevaRuta.setText("+ Nueva");
        toolBar.add(btnNuevaRuta);

        btnVerRuta.setText("Ver");
        toolBar.add(btnVerRuta);

        btnEditarRuta.setText("Editar");
        toolBar.add(btnEditarRuta);

        btnBorrarRuta.setForeground(new java.awt.Color(163, 45, 45));
        btnBorrarRuta.setText("Borrar");
        toolBar.add(btnBorrarRuta);

        btnMisListas.setText("Mis listas");
        btnMisListas.setFocusable(false);
        btnMisListas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMisListas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(btnMisListas);

        getContentPane().add(toolBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 740, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // getters para el controlador
    public javax.swing.JTable getTablaRutas()            { return tablaRutas; }
    public javax.swing.JButton getBtnNuevaRuta()         { return btnNuevaRuta; }
    public javax.swing.JButton getBtnVerRuta()           { return btnVerRuta; }
    public javax.swing.JButton getBtnEditarRuta()        { return btnEditarRuta; }
    public javax.swing.JButton getBtnBorrarRuta()        { return btnBorrarRuta; }
    public javax.swing.JButton getBtnCerrarSesion()      { return btnCerrarSesion; }
    public javax.swing.JButton getBtnMisListas()         { return btnMisListas; }
    public void setNombreUsuario(String nombre) { lblBienvenida.setText("Hola, " + nombre); }
    public void mostrarMensaje(String msg) { javax.swing.JOptionPane.showMessageDialog(this, msg); }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarRuta;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnEditarRuta;
    private javax.swing.JButton btnMisListas;
    private javax.swing.JButton btnNuevaRuta;
    private javax.swing.JButton btnVerRuta;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNombreApp;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JScrollPane scrollTabla;
    private javax.swing.JTable tablaRutas;
    private javax.swing.JToolBar toolBar;
    // End of variables declaration//GEN-END:variables
}
